### ISSUE TITLE
LGPLv3

### ISSUE THREAD

**Issue by 173210** [173210/psp2sdk#12]
Hi. I'm planning to use LGPLv3, because I noticed that it doesn't prohibit DRM. Please tell me your opinion, agree, disagree, or something.
@SMOKE5 @joshaxey @tomtomdu80 @Hykem

**Comment by joshaxey** [comment]
LGPL v3 makes sense to me. Agree.

**Comment by SMOKE5** [comment]
fine by me.

**Comment by tomtomdu80** [comment]
I agree as well, seems fine.

**Comment by Hykem** [comment]
Makes total sense, I agree too.

**Comment by 173210** [comment]
Updated successfully with commit e1e2299683a3d8c14b553913d3a9fdf5f0f1d6b6.
