### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by tomtomdu80** [173210/psp2sdk#13]
Is it fine to add SCE's error codes in the SDK ?

As 173210 pointed in issue #11, we should not refer to SCE's header files for legal issues, but error codes are defined in original pspsdk, as is, that's why I'm not sure if this is fine to add them or not.

**Comment by frangarcj** [comment]
how are you creating header files from?

**Comment by 173210** [comment]
Yes, but you should make sure that your reference doesn't not include any code from SCE except the name of error codes. The name of error codes doesn't produce copyrights. If it did, many open-sourced applications which use proprietary libraries would be illegal.

**Comment by 173210** [comment]
@frangarcj refer to rpcs3 or something. You can find some hints.

**Comment by tomtomdu80** [comment]
@173210 Thanks for the clarification.
