### ISSUE TITLE
stddef.h not there, but there?

### ISSUE THREAD

**Issue by zecoxao** [173210/psp2sdk#15]
http://pastie.org/private/x67kbgtlmlyshultbwu5pg
it's available of course, but configure can't find it :/

**Comment by psxdev** [comment]
os osx it's fine
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
However last commit in types.h has these problems:
../../src/include/psp2/types.h:231:5: error: unknown type name 'SceUMatrix4'
    SceUMatrix4 um;
    ^
SceUMatrix4 is not defined.
and ssize_t undefined
../../src/include/psp2/types.h:53:9: error: unknown type name 'ssize_t'




undefine

**Comment by tomtomdu80** [comment]
@psxdev the latest commit should fix these.

**Comment by 173210** [comment]
Use --verbose option to get more information.

**Comment by zecoxao** [comment]
with --verbose:
http://pastie.org/private/r5xqi7x62gselp1jxdpmq

**Comment by 173210** [comment]
The compiler is not for arm-none-eabi. Use a compiler for arm-none-eabi with --host option.
