### ISSUE TITLE
output from arm-none-eabi-objdump -D is empty with fixed elf files

### ISSUE THREAD

**Issue by psxdev** [173210/psp2sdk#20]
Tested in osx:

arm-none-eabi-objdump -D sample.elf

sample.elf:     file format elf32-littlearm

Disassembly of section .text:

00000000 <module_start>:
   0:	e92d4800 	push	{fp, lr}
   4:	e28db004 	add	fp, sp, #4
   8:	e24dd018 	sub	sp, sp, #24
   c:	e50b0008 	str	r0, [fp, #-8]
  10:	e50b100c 	str	r1, [fp, #-12]
  14:	e3003000 	movw	r3, #0
  18:	e3403000 	movt	r3, #0
  1c:	e3530000 	cmp	r3, #0
  20:	1a000002 	bne	30 <module_start+0x30>
  24:	e3003260 	movw	r3, #608	; 0x260
  28:	e3403000 	movt	r3, #0
  2c:	ea000001 	b	38 <module_start+0x38>
  30:	e3003000 	movw	r3, #0
  34:	e3403000 	movt	r3, #0
  38:	e3002000 	movw	r2, #0
  3c:	e3402000 	movt	r2, #0
  40:	e3520000 	cmp	r2, #0
  44:	0a000004 	beq	5c <module_start+0x5c>
  48:	e3002000 	movw	r2, #0
  4c:	e3402000 	movt	r2, #0
  50:	e5922000 	ldr	r2, [r2]
  54:	e1a0e002 	mov	lr, r2
  58:	ea000000 	b	60 <module_start+0x60>
  5c:	e3a0e020 	mov	lr, #32
  60:	e3002000 	movw	r2, #0
  64:	e3402000 	movt	r2, #0
  68:	e3520000 	cmp	r2, #0
  6c:	0a000003 	beq	80 <module_start+0x80>
  70:	e3002000 	movw	r2, #0
  74:	e3402000 	movt	r2, #0
  78:	e592c000 	ldr	ip, [r2]
  7c:	ea000000 	b	84 <module_start+0x84>
  80:	e3a0c601 	mov	ip, #1048576	; 0x100000
  84:	e3002000 	movw	r2, #0
  88:	e3402000 	movt	r2, #0
  8c:	e3520000 	cmp	r2, #0
  90:	0a000004 	beq	a8 <module_start+0xa8>
  94:	e3002000 	movw	r2, #0
  98:	e3402000 	movt	r2, #0
  9c:	e5922000 	ldr	r2, [r2]
  a0:	e1a01002 	mov	r1, r2
  a4:	ea000000 	b	ac <module_start+0xac>
  a8:	e3a01102 	mov	r1, #-2147483648	; 0x80000000
  ac:	e3002000 	movw	r2, #0
  b0:	e3402000 	movt	r2, #0
  b4:	e3520000 	cmp	r2, #0
  b8:	0a000003 	beq	cc <module_start+0xcc>
  bc:	e3002000 	movw	r2, #0
  c0:	e3402000 	movt	r2, #0
  c4:	e5922000 	ldr	r2, [r2]
  c8:	ea000000 	b	d0 <module_start+0xd0>
  cc:	e3a02807 	mov	r2, #458752	; 0x70000
  d0:	e58d1000 	str	r1, [sp]
  d4:	e58d2004 	str	r2, [sp, #4]
  d8:	e3002000 	movw	r2, #0
  dc:	e3402000 	movt	r2, #0
  e0:	e58d2008 	str	r2, [sp, #8]
  e4:	e1a00003 	mov	r0, r3
  e8:	e3001184 	movw	r1, #388	; 0x184
  ec:	e3401000 	movt	r1, #0
  f0:	e1a0200e 	mov	r2, lr
  f4:	e1a0300c 	mov	r3, ip
  f8:	ebffffc0 	bl	0 <module_start>
  fc:	e1a02000 	mov	r2, r0
 100:	e3003280 	movw	r3, #640	; 0x280
 104:	e3403000 	movt	r3, #0
 108:	e5832000 	str	r2, [r3]
 10c:	e3003280 	movw	r3, #640	; 0x280
 110:	e3403000 	movt	r3, #0
 114:	e5933000 	ldr	r3, [r3]
 118:	e3530000 	cmp	r3, #0
 11c:	ba000008 	blt	144 <module_start+0x144>
 120:	e3003280 	movw	r3, #640	; 0x280
 124:	e3403000 	movt	r3, #0
 128:	e5933000 	ldr	r3, [r3]
 12c:	e1a00003 	mov	r0, r3
 130:	e51b1008 	ldr	r1, [fp, #-8]
 134:	e51b200c 	ldr	r2, [fp, #-12]
 138:	ebffffb0 	bl	0 <module_start>
 13c:	e1a03000 	mov	r3, r0
 140:	ea000002 	b	150 <module_start+0x150>
 144:	e3003280 	movw	r3, #640	; 0x280
 148:	e3403000 	movt	r3, #0
 14c:	e5933000 	ldr	r3, [r3]
 150:	e1a00003 	mov	r0, r3
 154:	e24bd004 	sub	sp, fp, #4
 158:	e8bd8800 	pop	{fp, pc}

0000015c <module_stop>:
 15c:	e92d4800 	push	{fp, lr}
 160:	e28db004 	add	fp, sp, #4
 164:	e3003280 	movw	r3, #640	; 0x280
 168:	e3403000 	movt	r3, #0
 16c:	e5933000 	ldr	r3, [r3]
 170:	e1a00003 	mov	r0, r3
 174:	ebffffa1 	bl	0 <module_start>
 178:	e1a03000 	mov	r3, r0
 17c:	e1a00003 	mov	r0, r3
 180:	e8bd8800 	pop	{fp, pc}

00000184 <main>:
 184:	e92d4800 	push	{fp, lr}
 188:	e28db004 	add	fp, sp, #4
 18c:	e300026c 	movw	r0, #620	; 0x26c
 190:	e3400000 	movt	r0, #0
 194:	ebffff99 	bl	0 <module_start>
 198:	e3a03000 	mov	r3, #0
 19c:	e1a00003 	mov	r0, r3
 1a0:	e8bd8800 	pop	{fp, pc}

Disassembly of section .init:

000001a4 <.init>:
 1a4:	e24bd028 	sub	sp, fp, #40	; 0x28
 1a8:	e89d6ff0 	ldm	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, lr}
 1ac:	e12fff1e 	bx	lr

Disassembly of section .fini:

000001b0 <.fini>:
 1b0:	e24bd028 	sub	sp, fp, #40	; 0x28
 1b4:	e89d6ff0 	ldm	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, lr}
 1b8:	e12fff1e 	bx	lr

Disassembly of section .sceModuleInfo.rodata:

000001c0 <module_info>:
 1c0:	01010000 	mrseq	r0, (UNDEF: 1)
 1c4:	706d6173 	rsbvc	r6, sp, r3, ror r1
 1c8:	0000656c 	andeq	r6, r0, ip, ror #10
	...
 1e4:	00000240 	andeq	r0, r0, r0, asr #4
 1e8:	00000260 	andeq	r0, r0, r0, ror #4
 1ec:	00000260 	andeq	r0, r0, r0, ror #4
 1f0:	00000260 	andeq	r0, r0, r0, ror #4
	...
 208:	0000015c 	andeq	r0, r0, ip, asr r1
 20c:	00000278 	andeq	r0, r0, r8, ror r2
 210:	00000278 	andeq	r0, r0, r8, ror r2
 214:	00000278 	andeq	r0, r0, r8, ror r2
 218:	00000278 	andeq	r0, r0, r8, ror r2
 21c:	00000000 	andeq	r0, r0, r0

Disassembly of section .sceLib.ent:

00000220 <export>:
 220:	00000020 	andeq	r0, r0, r0, lsr #32
 224:	00020800 	andeq	r0, r2, r0, lsl #16
 228:	00000001 	andeq	r0, r0, r1
	...
 234:	00000258 	andeq	r0, r0, r8, asr r2
 238:	00000240 	andeq	r0, r0, r0, asr #4
 23c:	0000024c 	andeq	r0, r0, ip, asr #4

Disassembly of section .sceExport.rodata:

00000240 <export_top>:
 240:	935cd196 	cmpls	ip, #-2147483611	; 0x80000025
 244:	79f8e492 	ldmibvc	r8!, {r1, r4, r7, sl, sp, lr, pc}^
 248:	6c2224ba 	cfstrsvs	mvf2, [r2], #-744	; 0xfffffd18

0000024c <ents>:
 24c:	00000000 	andeq	r0, r0, r0
 250:	0000015c 	andeq	r0, r0, ip, asr r1
 254:	000001c0 	andeq	r0, r0, r0, asr #3

00000258 <name>:
 258:	6c737973 	ldclvs	9, cr7, [r3], #-460	; 0xfffffe34
 25c:	00006269 	andeq	r6, r0, r9, ror #4

Disassembly of section .sceImport.rodata:

00000260 <_SceLibKernel_stub_str>:
 260:	4c656353 	stclmi	3, cr6, [r5], #-332	; 0xfffffeb4
 264:	654b6269 	strbvs	r6, [fp, #-617]	; 0xfffffd97
 268:	6c656e72 	stclvs	14, cr6, [r5], #-456	; 0xfffffe38
	...

0000026d <_SceThreadmgr_stub_str>:
 26d:	54656353 	strbtpl	r6, [r5], #-851	; 0xfffffcad
 271:	61657268 	cmnvs	r5, r8, ror #4
 275:	72676d64 	rsbvc	r6, r7, #100, 26	; 0x1900
	...

0000027a <_SceLibc_stub_str>:
 27a:	4c656353 	stclmi	3, cr6, [r5], #-332	; 0xfffffeb4
 27e:	00636269 	rsbeq	r6, r3, r9, ror #4

Disassembly of section .sceFNID.rodata:

00000260 <.sceFNID.rodata>:
	...

Disassembly of section .sceFStub.rodata:

00000260 <.sceFStub.rodata>:
	...

Disassembly of section .rodata:

00000260 <.LC0>:
 260:	72657375 	rsbvc	r7, r5, #-738197503	; 0xd4000001
 264:	69616d5f 	stmdbvs	r1!, {r0, r1, r2, r3, r4, r6, r8, sl, fp, sp, lr}^
 268:	0000006e 	andeq	r0, r0, lr, rrx

0000026c <.LC1>:
 26c:	6c6c6568 	cfstr64vs	mvdx6, [ip], #-416	; 0xfffffe60
 270:	6f77206f 	svcvs	0x0077206f
 274:	00646c72 	rsbeq	r6, r4, r2, ror ip

Disassembly of section .eh_frame:

00000278 <__FRAME_END__>:
 278:	00000000 	andeq	r0, r0, r0

Disassembly of section .jcr:

0000027c <__JCR_END__>:
 27c:	00000000 	andeq	r0, r0, r0

Disassembly of section .bss:

00000280 <id>:
 280:	00000000 	andeq	r0, r0, r0

Disassembly of section .sce_libgen_mark:

00000284 <_SceLibKernel_0001_stub_head-0x3c>:
 284:	00000114 	andeq	r0, r0, r4, lsl r1
 288:	000002c0 	andeq	r0, r0, r0, asr #5
 28c:	00000000 	andeq	r0, r0, r0
 290:	c5c11ee7 	strbgt	r1, [r1, #3815]	; 0xee7
 294:	c5c11ee7 	strbgt	r1, [r1, #3815]	; 0xee7
 298:	00000114 	andeq	r0, r0, r4, lsl r1
 29c:	000002c0 	andeq	r0, r0, r0, asr #5
 2a0:	00000000 	andeq	r0, r0, r0
 2a4:	f08de149 			; <UNDEFINED> instruction: 0xf08de149
 2a8:	f08de149 			; <UNDEFINED> instruction: 0xf08de149
 2ac:	00000114 	andeq	r0, r0, r4, lsl r1
 2b0:	000002d8 	ldrdeq	r0, [r0], -r8
 2b4:	00000000 	andeq	r0, r0, r0
 2b8:	1bbde3d9 	blne	fef79224 <_NID_fopen+0xfefbafeb>
 2bc:	1bbde3d9 	blne	fef79228 <_NID_fopen+0xfefbafef>

000002c0 <_SceLibKernel_0001_stub_head>:
 2c0:	00000018 	andeq	r0, r0, r8, lsl r0
 2c4:	00000000 	andeq	r0, r0, r0
 2c8:	00000260 	andeq	r0, r0, r0, ror #4
 2cc:	00000001 	andeq	r0, r0, r1
 2d0:	00000000 	andeq	r0, r0, r0

000002d4 <_sce_package_version_SceLibKernel>:
 2d4:	00000000 	andeq	r0, r0, r0

000002d8 <_SceThreadmgr_0001_stub_head>:
 2d8:	00000018 	andeq	r0, r0, r8, lsl r0
 2dc:	00000000 	andeq	r0, r0, r0
 2e0:	0000026d 	andeq	r0, r0, sp, ror #4
 2e4:	00000001 	andeq	r0, r0, r1
 2e8:	00000000 	andeq	r0, r0, r0

000002ec <_sce_package_version_SceThreadmgr>:
 2ec:	00000000 	andeq	r0, r0, r0
 2f0:	00000114 	andeq	r0, r0, r4, lsl r1
 2f4:	00000304 	andeq	r0, r0, r4, lsl #6
 2f8:	00000000 	andeq	r0, r0, r0
 2fc:	9a004680 	bls	11d04 <_sce_package_version_SceLibc+0x119ec>
 300:	9a004680 	bls	11d08 <_sce_package_version_SceLibc+0x119f0>

00000304 <_SceLibc_0001_stub_head>:
 304:	00000018 	andeq	r0, r0, r8, lsl r0
 308:	00000000 	andeq	r0, r0, r0
 30c:	0000027a 	andeq	r0, r0, sl, ror r2
 310:	00000001 	andeq	r0, r0, r1
 314:	00000000 	andeq	r0, r0, r0

00000318 <_sce_package_version_SceLibc>:
 318:	00000000 	andeq	r0, r0, r0

Disassembly of section .comment:

00000000 <.comment>:
   0:	3a434347 	bcc	10d0d24 <_NID_realloc+0xa1b86a>
   4:	4e472820 	cdpmi	8, 4, cr2, cr7, cr0, {1}
   8:	34202955 	strtcc	r2, [r0], #-2389	; 0xfffff6ab
   c:	322e392e 	eorcc	r3, lr, #753664	; 0xb8000
	...

Disassembly of section .ARM.attributes:

00000000 <.ARM.attributes>:
   0:	00003c41 	andeq	r3, r0, r1, asr #24
   4:	61656100 	cmnvs	r5, r0, lsl #2
   8:	01006962 	tsteq	r0, r2, ror #18
   c:	00000032 	andeq	r0, r0, r2, lsr r0
  10:	726f4305 	rsbvc	r4, pc, #335544320	; 0x14000000
  14:	2d786574 	cfldr64cs	mvdx6, [r8, #-464]!	; 0xfffffe30
  18:	06003941 	streq	r3, [r0], -r1, asr #18
  1c:	0841070a 	stmdaeq	r1, {r1, r3, r8, r9, sl}^
  20:	0a020901 	beq	8242c <_sce_package_version_SceLibc+0x82114>
  24:	12010c03 	andne	r0, r1, #768	; 0x300
  28:	15011404 	strne	r1, [r1, #-1028]	; 0xfffffbfc
  2c:	18031701 	stmdane	r3, {r0, r8, r9, sl, ip}
  30:	1e011a01 	vmlane.f32	s2, s2, s2
  34:	24012206 	strcs	r2, [r1], #-518	; 0xfffffdfa
  38:	44012a01 	strmi	r2, [r1], #-2561	; 0xfffff5ff
  3c:	Address 0x000000000000003c is out of bounds.

Disassembly of section .sceRefs.rodata:

00000000 <.sceRefs.rodata>:
	...

Disassembly of section .sceStubs.text.SceLibKernel.sceKernelCreateThread:

00000000 <sceKernelCreateThread>:
   0:	e3e00000 	mvn	r0, #0
   4:	e12fff1e 	bx	lr
   8:	e320f000 	nop	{0}
   c:	00000000 	andeq	r0, r0, r0

Disassembly of section .sceStubs.text.SceLibKernel.sceKernelStartThread:

00000000 <sceKernelStartThread>:
   0:	e3e00000 	mvn	r0, #0
   4:	e12fff1e 	bx	lr
   8:	e320f000 	nop	{0}
   c:	00000000 	andeq	r0, r0, r0

Disassembly of section .sceStubs.text.SceThreadmgr.sceKernelDeleteThread:

00000000 <sceKernelDeleteThread>:
   0:	e3e00000 	mvn	r0, #0
   4:	e12fff1e 	bx	lr
   8:	e320f000 	nop	{0}
   c:	00000000 	andeq	r0, r0, r0

Disassembly of section .sceStubs.text.SceLibc.printf:

00000000 <printf>:
   0:	e3e00000 	mvn	r0, #0
   4:	e12fff1e 	bx	lr
   8:	e320f000 	nop	{0}
   c:	00000000 	andeq	r0, r0, r0

------

arm-none-eabi-objdump -D sample_fix.elf

sample_fixup.elf:     file format elf32-littlearm

**Comment by 173210** [comment]
It's fine because psp2-fixup strips section information.
