### ISSUE TITLE
psp2fixup / elf.c : default sceModuleInfo

### ISSUE THREAD

**Issue by yne** [173210/psp2sdk#21]
A missing .sceModuleInfo section should not be fatal.
However it should throw a warning on stderr and insert a generic sceModuleInfo instead :
```
{
  .attr = 0,
  .ver = 0,
  .name = "",
  .type = 0,
  .gp = NULL,
  .expTop = [1],
  .expBtm = [1],
  .impTop = [1],
  .impBtm = [1],
  .nid = 0,
  .start = [2],
  .stop = [2],
  .exidxTop = [1],
  .exidxBtm = [1],
  .extabTop = [1],
  .extabBtm = [1],
}
//notes :
//[1] : Should be found by scanning the sections
//[2] : Should be found by scanning the symbol sections (or defaulting to 00000000)
```
This would allow any C project to be compilable on the SDK without any modification !
(beside the fact that your crt0 don't split the args/argp into argc/argv)

BTW, love the way this SDK is organized (except the `goto` coding style ;-) ).

**Comment by 173210** [comment]
It may be implemented by crt0, but I won't because it doesn't make differences so much and properties like name and version should be specified by a developer. I won't do that.

What's wrong with `goto`?
