### ISSUE TITLE
There are few stub libraries

### ISSUE THREAD

**Issue by 173210** [173210/psp2sdk#3]
Make new libraries!

Use [SceLibMonoBridge_stub.S](https://github.com/173210/psp2sdk/commit/52206780d36bbf0bbf071d441ab0cce84de5148f) as a reference.

You can find libraries from those source.
* [rpcs3](https://github.com/RPCS3/rpcs3/tree/master/rpcs3/Emu/ARMv7/Modules)

[vitasploit](https://github.com/Hykem/vitasploit/blob/master/server.py) has a function to extract imports and exports.

Please make sure that your function names start with sce-. Actually SceLibMonoBridge_stub.S has functions which doesn't start with sce-, but it's a special case.

**Comment by Hykem** [comment]
I've created a pull request with some of the most important modules. I'll be adding more in the future.
A few parameters are missing (PSP2_IMPORT_HEAD nid, for example), which I'll add later on.

**Comment by 173210** [comment]
I think you can calculate easily. Anyway, thanks for your commit!

**Comment by 173210** [comment]
It now supports autotools with commit d1096a88674a9f083f8dcb05c67c3f71974895e4.
Please make sure that you add a proper Makefile.am when you add a new stub library.

**Comment by 173210** [comment]
I think there are many libraries now, so I close this issue. Thank everyone who made libraries!
