### ISSUE TITLE
Logo submission

### ISSUE THREAD

**Issue by joshaxey** [173210/psp2sdk#37]
Please cast a yes or no vote for the logo and I shall add (or not) it to the readme/front page and wiki.

Going on the Playstation button colour theme + Yifan's rejuvenate theme.

FYI: Font is different enough to not cause any legal issues.

![PSP2SDK](https://dl.dropboxusercontent.com/u/46691658/psp2sdk_xsmall.png)

**Comment by MysteryDash** [comment]
I love it !
So, yes.

**Comment by tomtomdu80** [comment]
This really is a nice one, agreed :+1:

**Comment by korgano** [comment]
Looks great! So that's a YES from me.

**Comment by ribbid987** [comment]
The logo is nice. Yes.

**Comment by frangarcj** [comment]
Great!!!

**Comment by SMOKE5** [comment]
Love it

**Comment by Ryp** [comment]
Very nice =) Although a reminder of the color of the original Playstation would be cool

**Comment by Gamesonic** [comment]
Very Incredible and Very beautiful

**Comment by psxdev** [comment]
fine

**Comment by 173210** [comment]
Added as the logo for doxygen with commit 48b119c17e53c3ee9eb036393bc3fc89aa75b5a0.
