### ISSUE TITLE
No errno

### ISSUE THREAD

**Issue by 173210** [173210/psp2sdk#48]
src/include/errno.h lacks error numbers.

**Comment by Hykem** [comment]
Added the error codes in the last commit.

**Comment by 173210** [comment]
The error codes should be for standard c library. However, it seems possible to calculate the numbers.
s/SCE_ERROR_ERRNO_//g
s/800100//g
And usually those numbers are declared as decimal ones.

**Comment by 173210** [comment]
Fixed with commit 22f8150167b16dfd7639a79151d038e04e01c06d. I have not confirmed, but I'll close this issue for a while.
(Most parts of PSP2SDK are not confirmed :P)
