### ISSUE TITLE
psp2-fixup (32-bit) crashes on Windows (64-bit) when used on FTPVita

### ISSUE THREAD

**Issue by MrNetrix** [173210/psp2sdk#52]
Occurs with the nightly build and local build. It appears that some relocations are messed up. Works fine on Ubuntu.

Backtrace:
0x00404dcb in convRelToRela (scns=0x8a4188, segs=0x8a2f90, symtab=0x8a6528, relScns=0x8aefb0, relShnum=8)
at rel.c:140
0x0040427b in updateElf (elf=0x28fec0) at elf.c:202
0x00403a78 in main (argc=5, argv=0x8a1b10) at psp2-fixup.c:109

https://github.com/xerpi/FTPVita

**Comment by 173210** [comment]
Duplicated with issue #45 .
