### ISSUE TITLE
tools need Makefile.in 

### ISSUE THREAD

**Issue by psxdev** [173210/psp2sdk#9]
bigmini:tools bigboss$ ./autogen.sh
**Warning**: I am going to run `configure' with no arguments.
If you wish to pass any to it, please specify them on the
`./autogen.sh' command line.

Running aclocal...
Running automake --gnu  ...
configure.ac:37: error: required file 'psp2-fixup/Makefile.in' not found
configure.ac:37: error: required file 'psp2-fixup-lib/Makefile.in' not found
**Error**: automake failed.

compiling by hand with embed elf.h included in your last commit give me:

bigmini:psp2-fixup bigboss$ ls
psp2-fixup.c
bigmini:psp2-fixup bigboss$ gcc -I../include psp2-fixup.c
In file included from psp2-fixup.c:19:
../include/elf.h:972:10: fatal error: 'bits/auxv.h' file not found
#include <bits/auxv.h>

**Comment by 173210** [comment]
That's strange. automake should produce Makefile.in.
I'll remove reference to bits/auxv.h.

**Comment by 173210** [comment]
The reference to bits/auxv.h was removed with commit 335ab09e93499e09052d531e56b97e9f59ed41e9.

**Comment by psxdev** [comment]
Ok compile fine now by hand. I believe that we need Makefile.am on tools/psp2-fixup and tools/psp2-fixup-lib there are only C file on it and autogen.sh does not generate Makefiles if it does not find Makefile.am

Adding empty Makefile.am solve generation of Makefiles but we would need add custom target on it to compile wit make

**Comment by 173210** [comment]
I had forgot to commit them. Now I made commit d93dc9b6750ab6a164b9556f0bdccb8918d8cb8b. It should solve the issue.

**Comment by psxdev** [comment]
fixed
